### ISSUE TITLE
rename repository to py-zopfli?

### ISSUE THREAD

**Issue by anthrotype** [obp/py-zopfli#4]
I think it'd be better if the repository is named `https://github.com/obp/py-zopfli` (like the old upstream https://github.com/wnyc/py-zopfli), instead of simply `zopfli`.
The current name could be confused with the https://github.com/google/zopfli project, whereas this is the only the python bindings, not the C library.

@adamdeprince shall we rename it to py-zopfli?

**Comment by lcd1232** [comment]
@anthrotype yes, it's a good idea

**Comment by anthrotype** [comment]
https://github.com/obp/py-zopfli

done
